Added new entity.
Blackolf931/CV.Back pull request #24
Opened 2022-07-19 10:45 UTC by VideoRab

2022-07-19 10:48 UTC, hromau approved these changes

2022-07-19 11:08 UTC, eeveesharp approved these changes

2022-07-19 12:00 UTC, Blackolf931 requested changes

2022-07-19 12:00 UTC, Blackolf931 commented on CV/CV.DAL/Entities/EmployeeEntity.cs
> +        public string Name { get; set; }
Get rid warnings

2022-07-19 12:45 UTC, sfrolov8a approved these changes

2022-07-19 12:51 UTC, hromau requested changes

2022-07-19 12:52 UTC, Blackolf931 requested changes

2022-07-19 12:57 UTC, VideoRab commented on CV/CV.DAL/Entities/EmployeeEntity.cs
> +        public string Name { get; set; } = string.Empty;
It's value will be used in default.

2022-07-19 13:00 UTC, Blackolf931 commented on CV/CV.DAL/Entities/EmployeeEntity.cs
> +        public string Name { get; set; } = string.Empty;
Okay, tell me please, How can an employee have an empty first name< last name and patronomic? Is it possible?

2022-07-19 13:10 UTC, VideoRab commented on CV/CV.DAL/Entities/EmployeeEntity.cs
> +        public string Name { get; set; } = string.Empty;
No, it isn't. I can set default value to null, if it will be better.

2022-07-19 13:11 UTC, VideoRab commented on CV/CV.DAL/Entities/EmployeeEntity.cs
> +        public string Name { get; set; } = string.Empty;
Otherwise will be 3 warnings in this class.

2022-07-20 05:49 UTC, Blackolf931 approved these changes

2022-07-20 08:03 UTC, eeveesharp approved these changes

2022-07-20 08:03 UTC, merged